#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 CARLOS Contributors
# Test stub for useradd — records the invocation, succeeds.
echo "useradd $*" >> "${STUBLOG:-/dev/null}"
exit 0
